### PR TITLE
-3b: Use array elision

### PR DESCRIPTION
**Pull request by subzey**
Changes description:
```diff
-… .filter(v=>v-1023||…)
+… .filter(v=>v^1023||…)
````

In this exact case there's no difference how to compare 1023 with `v`: algebraically or binary. This small change allows `map`'ped array to contain `undefined`s. So we can use elision:

```diff
-[s=0,0,0,0,...b].filter(…
+[s=0,,,,...b].filter(…
```

_That `,,,,...` doesn't even look like a JS code 😃_

One thing that bothers me is `v-1023+P`, this statement would work the other way if the `P == 1023`. But `P` is an array... I don't quite understand what happens here, so I definitely need your review.

### CODE REVIEW

**Comment by veu** [comment]
The long version of `v-1023+P` would be `v!=1023||P!=0`. Unfortunately with `^` you can no longer use the second `+` and `|` doesn’t work with an array. In the end you’d lose the bytes again that you saved though I’d love to see a solution.

**Comment by subzey** [comment]
Would it be a problem if we just leave that part as is?

Here's a `v-1023+P` breakdown (if I've understood you correctly):

|               | v = `0`          | v = `undefined` |
|---------------|------------------|-----------------|
| P = `0`       | `-1023`          | ~`"NaN0"`~ `NaN`      |
| P = `[1,2,3]` | `"-10231,2,3"` | `"NaN1,2,3"`  |

~All these exprs are truthy with `v`  both `0` and `undefined`~

UPD: My bad, undefined - 1023 + 0 = NaN.

Does `P` equal `0` only on init phase, or can it become `0` any time?

**Comment by veu** [comment]
That won’t work. `NaN+0` is `NaN` which is falsy.

**Comment by veu** [comment]
Idea: if I can get rid of `v-1023+P` entirely, I can implement your improvement.

**Comment by veu** [comment]
`P` becomes `0` after a piece landed and before a new one is selected.

**Comment by veu** [comment]
Actually, there’s another problem with using `undefined`. In `Array.map` `undefined` values are skipped. The result is a shortened board if you clear more than one line. :/

**Comment by subzey** [comment]
Uh-oh! That definitely wouldn't be easy to overcome, so I'd better close this PR.

Thanks for your time!

_Btw, this project is awesome!_

**Comment by veu** [comment]
Don’t worry. I saved 2b in c0d312a17c030f3ba8d96b99227d54d9b4a0fe3d using your `^` idea and some of your code.

Turns out that while an array like `[,,,]` isn’t usable in `Array.map`, the copied version `[...[,,,]]` works just fine.

**Pull request closed without merging**
